version: '3.4'

services:
  jeancarlos.grandezaguilar.alumnos.services:
    image: ${DOCKER_REGISTRY-}jeancarlosgrandezaguilaralumnos
    build:
      context: .
      dockerfile: Backend/Domain/Escuela/jeancarlos.grandezaguilar.alumnos.services/Dockerfile
    ports:
      - 8082:80
      - 8083:443
    networks:
      - backend
  jeancarlos.grandezaguilar.security.services:
    image: ${DOCKER_REGISTRY-}jeancarlosgrandezaguilarsecurity
    build:
      context: .
      dockerfile: Backend/Infrastructure/Security/jeancarlos.grandezaguilar.security.services/Dockerfile
    ports:
      - 8084:80
      - 8085:443
    networks:
      - backend
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password1234
    ports:
      - 1434:1433
    networks:
      - backend  
networks:
  backend:
    name: backend
    driver: bridge

