// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using jeancarlos.grandezaguilar.alumnos.services.Infrastructure.Persistence.Contexts;

#nullable disable

namespace jeancarlos.grandezaguilar.alumnos.services.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EscuelaContext))]
    partial class EscuelaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("jeancarlos.grandezaguilar.alumnos.services.Domain.Escuela.Entidades.Alumno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("ApeMaterno")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Ape_Materno");

                    b.Property<string>("ApePaterno")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Ape_Paterno");

                    b.Property<DateTime?>("FechaNac")
                        .HasColumnType("date");

                    b.Property<string>("Ndocumento")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NDocumento");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Tdocumento")
                        .HasColumnType("int")
                        .HasColumnName("TDocumento");

                    b.HasKey("Id");

                    b.ToTable("Alumnos");
                });

            modelBuilder.Entity("jeancarlos.grandezaguilar.alumnos.services.Domain.Escuela.Entidades.Curso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Descripcion")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("jeancarlos.grandezaguilar.alumnos.services.Domain.Escuela.Entidades.Matricula", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("FechaRegistro")
                        .HasColumnType("datetime");

                    b.Property<Guid>("IdAlumno")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdCurso")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdAlumno");

                    b.HasIndex("IdCurso");

                    b.ToTable("Matricula", (string)null);
                });

            modelBuilder.Entity("jeancarlos.grandezaguilar.alumnos.services.Domain.Escuela.Entidades.Matricula", b =>
                {
                    b.HasOne("jeancarlos.grandezaguilar.alumnos.services.Domain.Escuela.Entidades.Alumno", "IdAlumnoNavigation")
                        .WithMany("Matriculas")
                        .HasForeignKey("IdAlumno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Matricula_Alumno");

                    b.HasOne("jeancarlos.grandezaguilar.alumnos.services.Domain.Escuela.Entidades.Curso", "IdCursoNavigation")
                        .WithMany("Matriculas")
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Matricula_Curso");

                    b.Navigation("IdAlumnoNavigation");

                    b.Navigation("IdCursoNavigation");
                });

            modelBuilder.Entity("jeancarlos.grandezaguilar.alumnos.services.Domain.Escuela.Entidades.Alumno", b =>
                {
                    b.Navigation("Matriculas");
                });

            modelBuilder.Entity("jeancarlos.grandezaguilar.alumnos.services.Domain.Escuela.Entidades.Curso", b =>
                {
                    b.Navigation("Matriculas");
                });
#pragma warning restore 612, 618
        }
    }
}
