// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using jeancarlos.grandezaguilar.alumnos.services.Domain.Escuela.Entidades;
using jeancarlos.grandezaguilar.alumnos.services.Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace jeancarlos.grandezaguilar.alumnos.services.Infrastructure.Persistence.Contexts.Configurations
{
    public partial class AlumnoConfiguration : IEntityTypeConfiguration<Alumno>
    {
        public void Configure(EntityTypeBuilder<Alumno> entity)
        {
            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.ApeMaterno)
            .HasMaxLength(50)
            .IsUnicode(false)
            .HasColumnName("Ape_Materno");
            entity.Property(e => e.ApePaterno)
            .HasMaxLength(50)
            .IsUnicode(false)
            .HasColumnName("Ape_Paterno");
            entity.Property(e => e.FechaNac).HasColumnType("date");
            entity.Property(e => e.Ndocumento)
            .HasMaxLength(50)
            .IsUnicode(false)
            .HasColumnName("NDocumento");
            entity.Property(e => e.Nombre)
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.Tdocumento).HasColumnName("TDocumento");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Alumno> entity);
    }
}
