// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using jeancarlos.grandezaguilar.alumnos.services.Domain.Escuela.Entidades;
using jeancarlos.grandezaguilar.alumnos.services.Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace jeancarlos.grandezaguilar.alumnos.services.Infrastructure.Persistence.Contexts.Configurations
{
    public partial class CursoConfiguration : IEntityTypeConfiguration<Curso>
    {
        public void Configure(EntityTypeBuilder<Curso> entity)
        {
            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.Descripcion).IsUnicode(false);
            entity.Property(e => e.Nombre)
            .HasMaxLength(50)
            .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Curso> entity);
    }
}
