// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace jeancarlos.grandezaguilar.alumnos.services.Domain.Escuela.Entidades;

public partial class Alumno
{
    public Guid Id { get; set; }

    public string ApePaterno { get; set; }

    public string ApeMaterno { get; set; }

    public string Nombre { get; set; }

    public DateTime? FechaNac { get; set; }

    public int? Tdocumento { get; set; }

    public string Ndocumento { get; set; }

    public virtual ICollection<Matricula> Matriculas { get; set; } = new List<Matricula>();
}