// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace jeancarlos.grandezaguilar.alumnos.services.Domain.Escuela.Entidades;

public partial class Matricula
{
    public Guid Id { get; set; }

    public Guid IdAlumno { get; set; }

    public Guid IdCurso { get; set; }

    public DateTime? FechaRegistro { get; set; }

    public virtual Alumno IdAlumnoNavigation { get; set; }

    public virtual Curso IdCursoNavigation { get; set; }
}