// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using jeancarlos.grandezaguilar.alumnos.services.Domain.Escuela.Entidades;
using jeancarlos.grandezaguilar.alumnos.services.Infrastructure.Persistence.Contexts.Configurations;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
#nullable disable

namespace jeancarlos.grandezaguilar.alumnos.services.Infrastructure.Persistence.Contexts;

public partial class EscuelaContext : DbContext
{
    public EscuelaContext(DbContextOptions<EscuelaContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Alumno> Alumnos { get; set; }

    public virtual DbSet<Curso> Cursos { get; set; }

    public virtual DbSet<Matricula> Matriculas { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
            modelBuilder.ApplyConfiguration(new Configurations.AlumnoConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.CursoConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.MatriculaConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
